// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radar_messages.proto

package is.hellos.demos.models.protos;

public final class RadarMessages {
    private RadarMessages() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }
    public interface FeatureVectorOrBuilder extends
            // @@protoc_insertion_point(interface_extends:hello.FeatureVector)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string id = 1;</code>
         */
        boolean hasId();
        /**
         * <code>optional string id = 1;</code>
         */
        java.lang.String getId();
        /**
         * <code>optional string id = 1;</code>
         */
        com.google.protobuf.ByteString
        getIdBytes();

        /**
         * <code>optional string device_id = 2;</code>
         */
        boolean hasDeviceId();
        /**
         * <code>optional string device_id = 2;</code>
         */
        java.lang.String getDeviceId();
        /**
         * <code>optional string device_id = 2;</code>
         */
        com.google.protobuf.ByteString
        getDeviceIdBytes();

        /**
         * <code>repeated float floatfeats = 3;</code>
         */
        java.util.List<java.lang.Float> getFloatfeatsList();
        /**
         * <code>repeated float floatfeats = 3;</code>
         */
        int getFloatfeatsCount();
        /**
         * <code>repeated float floatfeats = 3;</code>
         */
        float getFloatfeats(int index);

        /**
         * <code>optional int64 sequence_number = 4;</code>
         */
        boolean hasSequenceNumber();
        /**
         * <code>optional int64 sequence_number = 4;</code>
         */
        long getSequenceNumber();
    }
    /**
     * Protobuf type {@code hello.FeatureVector}
     */
    public static final class FeatureVector extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:hello.FeatureVector)
            FeatureVectorOrBuilder {
        // Use FeatureVector.newBuilder() to construct.
        private FeatureVector(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private FeatureVector(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final FeatureVector defaultInstance;
        public static FeatureVector getDefaultInstance() {
            return defaultInstance;
        }

        public FeatureVector getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private FeatureVector(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                                   extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            id_ = bs;
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            deviceId_ = bs;
                            break;
                        }
                        case 29: {
                            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                                floatfeats_ = new java.util.ArrayList<java.lang.Float>();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            floatfeats_.add(input.readFloat());
                            break;
                        }
                        case 26: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                                floatfeats_ = new java.util.ArrayList<java.lang.Float>();
                                mutable_bitField0_ |= 0x00000004;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                floatfeats_.add(input.readFloat());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000004;
                            sequenceNumber_ = input.readInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                    floatfeats_ = java.util.Collections.unmodifiableList(floatfeats_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return is.hellos.demos.models.protos.RadarMessages.internal_static_hello_FeatureVector_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return is.hellos.demos.models.protos.RadarMessages.internal_static_hello_FeatureVector_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            is.hellos.demos.models.protos.RadarMessages.FeatureVector.class, is.hellos.demos.models.protos.RadarMessages.FeatureVector.Builder.class);
        }

        public static com.google.protobuf.Parser<FeatureVector> PARSER =
                new com.google.protobuf.AbstractParser<FeatureVector>() {
                    public FeatureVector parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new FeatureVector(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<FeatureVector> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int ID_FIELD_NUMBER = 1;
        private java.lang.Object id_;
        /**
         * <code>optional string id = 1;</code>
         */
        public boolean hasId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string id = 1;</code>
         */
        public java.lang.String getId() {
            java.lang.Object ref = id_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    id_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string id = 1;</code>
         */
        public com.google.protobuf.ByteString
        getIdBytes() {
            java.lang.Object ref = id_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                id_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DEVICE_ID_FIELD_NUMBER = 2;
        private java.lang.Object deviceId_;
        /**
         * <code>optional string device_id = 2;</code>
         */
        public boolean hasDeviceId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string device_id = 2;</code>
         */
        public java.lang.String getDeviceId() {
            java.lang.Object ref = deviceId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    deviceId_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string device_id = 2;</code>
         */
        public com.google.protobuf.ByteString
        getDeviceIdBytes() {
            java.lang.Object ref = deviceId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                deviceId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int FLOATFEATS_FIELD_NUMBER = 3;
        private java.util.List<java.lang.Float> floatfeats_;
        /**
         * <code>repeated float floatfeats = 3;</code>
         */
        public java.util.List<java.lang.Float>
        getFloatfeatsList() {
            return floatfeats_;
        }
        /**
         * <code>repeated float floatfeats = 3;</code>
         */
        public int getFloatfeatsCount() {
            return floatfeats_.size();
        }
        /**
         * <code>repeated float floatfeats = 3;</code>
         */
        public float getFloatfeats(int index) {
            return floatfeats_.get(index);
        }

        public static final int SEQUENCE_NUMBER_FIELD_NUMBER = 4;
        private long sequenceNumber_;
        /**
         * <code>optional int64 sequence_number = 4;</code>
         */
        public boolean hasSequenceNumber() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int64 sequence_number = 4;</code>
         */
        public long getSequenceNumber() {
            return sequenceNumber_;
        }

        private void initFields() {
            id_ = "";
            deviceId_ = "";
            floatfeats_ = java.util.Collections.emptyList();
            sequenceNumber_ = 0L;
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getDeviceIdBytes());
            }
            for (int i = 0; i < floatfeats_.size(); i++) {
                output.writeFloat(3, floatfeats_.get(i));
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt64(4, sequenceNumber_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getDeviceIdBytes());
            }
            {
                int dataSize = 0;
                dataSize = 4 * getFloatfeatsList().size();
                size += dataSize;
                size += 1 * getFloatfeatsList().size();
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(4, sequenceNumber_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static is.hellos.demos.models.protos.RadarMessages.FeatureVector parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static is.hellos.demos.models.protos.RadarMessages.FeatureVector parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static is.hellos.demos.models.protos.RadarMessages.FeatureVector parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static is.hellos.demos.models.protos.RadarMessages.FeatureVector parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static is.hellos.demos.models.protos.RadarMessages.FeatureVector parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static is.hellos.demos.models.protos.RadarMessages.FeatureVector parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        public static is.hellos.demos.models.protos.RadarMessages.FeatureVector parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        public static is.hellos.demos.models.protos.RadarMessages.FeatureVector parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static is.hellos.demos.models.protos.RadarMessages.FeatureVector parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static is.hellos.demos.models.protos.RadarMessages.FeatureVector parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(is.hellos.demos.models.protos.RadarMessages.FeatureVector prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code hello.FeatureVector}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:hello.FeatureVector)
                is.hellos.demos.models.protos.RadarMessages.FeatureVectorOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return is.hellos.demos.models.protos.RadarMessages.internal_static_hello_FeatureVector_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return is.hellos.demos.models.protos.RadarMessages.internal_static_hello_FeatureVector_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                is.hellos.demos.models.protos.RadarMessages.FeatureVector.class, is.hellos.demos.models.protos.RadarMessages.FeatureVector.Builder.class);
            }

            // Construct using is.hellos.demos.models.protos.RadarMessages.FeatureVector.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }
            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                id_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                deviceId_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                floatfeats_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000004);
                sequenceNumber_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return is.hellos.demos.models.protos.RadarMessages.internal_static_hello_FeatureVector_descriptor;
            }

            public is.hellos.demos.models.protos.RadarMessages.FeatureVector getDefaultInstanceForType() {
                return is.hellos.demos.models.protos.RadarMessages.FeatureVector.getDefaultInstance();
            }

            public is.hellos.demos.models.protos.RadarMessages.FeatureVector build() {
                is.hellos.demos.models.protos.RadarMessages.FeatureVector result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public is.hellos.demos.models.protos.RadarMessages.FeatureVector buildPartial() {
                is.hellos.demos.models.protos.RadarMessages.FeatureVector result = new is.hellos.demos.models.protos.RadarMessages.FeatureVector(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.id_ = id_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.deviceId_ = deviceId_;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    floatfeats_ = java.util.Collections.unmodifiableList(floatfeats_);
                    bitField0_ = (bitField0_ & ~0x00000004);
                }
                result.floatfeats_ = floatfeats_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.sequenceNumber_ = sequenceNumber_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof is.hellos.demos.models.protos.RadarMessages.FeatureVector) {
                    return mergeFrom((is.hellos.demos.models.protos.RadarMessages.FeatureVector)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(is.hellos.demos.models.protos.RadarMessages.FeatureVector other) {
                if (other == is.hellos.demos.models.protos.RadarMessages.FeatureVector.getDefaultInstance()) return this;
                if (other.hasId()) {
                    bitField0_ |= 0x00000001;
                    id_ = other.id_;
                    onChanged();
                }
                if (other.hasDeviceId()) {
                    bitField0_ |= 0x00000002;
                    deviceId_ = other.deviceId_;
                    onChanged();
                }
                if (!other.floatfeats_.isEmpty()) {
                    if (floatfeats_.isEmpty()) {
                        floatfeats_ = other.floatfeats_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                    } else {
                        ensureFloatfeatsIsMutable();
                        floatfeats_.addAll(other.floatfeats_);
                    }
                    onChanged();
                }
                if (other.hasSequenceNumber()) {
                    setSequenceNumber(other.getSequenceNumber());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                is.hellos.demos.models.protos.RadarMessages.FeatureVector parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (is.hellos.demos.models.protos.RadarMessages.FeatureVector) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.lang.Object id_ = "";
            /**
             * <code>optional string id = 1;</code>
             */
            public boolean hasId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>optional string id = 1;</code>
             */
            public java.lang.String getId() {
                java.lang.Object ref = id_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        id_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string id = 1;</code>
             */
            public com.google.protobuf.ByteString
            getIdBytes() {
                java.lang.Object ref = id_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    id_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string id = 1;</code>
             */
            public Builder setId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string id = 1;</code>
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = getDefaultInstance().getId();
                onChanged();
                return this;
            }
            /**
             * <code>optional string id = 1;</code>
             */
            public Builder setIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object deviceId_ = "";
            /**
             * <code>optional string device_id = 2;</code>
             */
            public boolean hasDeviceId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            /**
             * <code>optional string device_id = 2;</code>
             */
            public java.lang.String getDeviceId() {
                java.lang.Object ref = deviceId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        deviceId_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string device_id = 2;</code>
             */
            public com.google.protobuf.ByteString
            getDeviceIdBytes() {
                java.lang.Object ref = deviceId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    deviceId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string device_id = 2;</code>
             */
            public Builder setDeviceId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                deviceId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string device_id = 2;</code>
             */
            public Builder clearDeviceId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                deviceId_ = getDefaultInstance().getDeviceId();
                onChanged();
                return this;
            }
            /**
             * <code>optional string device_id = 2;</code>
             */
            public Builder setDeviceIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                deviceId_ = value;
                onChanged();
                return this;
            }

            private java.util.List<java.lang.Float> floatfeats_ = java.util.Collections.emptyList();
            private void ensureFloatfeatsIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    floatfeats_ = new java.util.ArrayList<java.lang.Float>(floatfeats_);
                    bitField0_ |= 0x00000004;
                }
            }
            /**
             * <code>repeated float floatfeats = 3;</code>
             */
            public java.util.List<java.lang.Float>
            getFloatfeatsList() {
                return java.util.Collections.unmodifiableList(floatfeats_);
            }
            /**
             * <code>repeated float floatfeats = 3;</code>
             */
            public int getFloatfeatsCount() {
                return floatfeats_.size();
            }
            /**
             * <code>repeated float floatfeats = 3;</code>
             */
            public float getFloatfeats(int index) {
                return floatfeats_.get(index);
            }
            /**
             * <code>repeated float floatfeats = 3;</code>
             */
            public Builder setFloatfeats(
                    int index, float value) {
                ensureFloatfeatsIsMutable();
                floatfeats_.set(index, value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated float floatfeats = 3;</code>
             */
            public Builder addFloatfeats(float value) {
                ensureFloatfeatsIsMutable();
                floatfeats_.add(value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated float floatfeats = 3;</code>
             */
            public Builder addAllFloatfeats(
                    java.lang.Iterable<? extends java.lang.Float> values) {
                ensureFloatfeatsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, floatfeats_);
                onChanged();
                return this;
            }
            /**
             * <code>repeated float floatfeats = 3;</code>
             */
            public Builder clearFloatfeats() {
                floatfeats_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            private long sequenceNumber_ ;
            /**
             * <code>optional int64 sequence_number = 4;</code>
             */
            public boolean hasSequenceNumber() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }
            /**
             * <code>optional int64 sequence_number = 4;</code>
             */
            public long getSequenceNumber() {
                return sequenceNumber_;
            }
            /**
             * <code>optional int64 sequence_number = 4;</code>
             */
            public Builder setSequenceNumber(long value) {
                bitField0_ |= 0x00000008;
                sequenceNumber_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional int64 sequence_number = 4;</code>
             */
            public Builder clearSequenceNumber() {
                bitField0_ = (bitField0_ & ~0x00000008);
                sequenceNumber_ = 0L;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:hello.FeatureVector)
        }

        static {
            defaultInstance = new FeatureVector(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:hello.FeatureVector)
    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_hello_FeatureVector_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_hello_FeatureVector_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\024radar_messages.proto\022\005hello\"[\n\rFeature" +
                        "Vector\022\n\n\002id\030\001 \001(\t\022\021\n\tdevice_id\030\002 \001(\t\022\022\n" +
                        "\nfloatfeats\030\003 \003(\002\022\027\n\017sequence_number\030\004 \001" +
                        "(\003B.\n\035is.hellos.demos.models.protosB\rRad" +
                        "arMessages"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                                                new com.google.protobuf.Descriptors.FileDescriptor[] {
                                                }, assigner);
        internal_static_hello_FeatureVector_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_hello_FeatureVector_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_hello_FeatureVector_descriptor,
                new java.lang.String[] { "Id", "DeviceId", "Floatfeats", "SequenceNumber", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
