// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: respiration_health.proto

package is.hellos.demos.models.protos;

public final class RespirationHealth {
  private RespirationHealth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code hello.ResiprationHealthState}
   */
  public enum ResiprationHealthState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NOBODY_PRESENT = 0;</code>
     */
    NOBODY_PRESENT(0, 0),
    /**
     * <code>PERSON_IS_PRESENT = 1;</code>
     */
    PERSON_IS_PRESENT(1, 1),
    /**
     * <code>PERSON_IS_PRESENT_NOT_BREATHING = 2;</code>
     */
    PERSON_IS_PRESENT_NOT_BREATHING(2, 2),
    ;

    /**
     * <code>NOBODY_PRESENT = 0;</code>
     */
    public static final int NOBODY_PRESENT_VALUE = 0;
    /**
     * <code>PERSON_IS_PRESENT = 1;</code>
     */
    public static final int PERSON_IS_PRESENT_VALUE = 1;
    /**
     * <code>PERSON_IS_PRESENT_NOT_BREATHING = 2;</code>
     */
    public static final int PERSON_IS_PRESENT_NOT_BREATHING_VALUE = 2;


    public final int getNumber() { return value; }

    public static ResiprationHealthState valueOf(int value) {
      switch (value) {
        case 0: return NOBODY_PRESENT;
        case 1: return PERSON_IS_PRESENT;
        case 2: return PERSON_IS_PRESENT_NOT_BREATHING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResiprationHealthState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ResiprationHealthState>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResiprationHealthState>() {
            public ResiprationHealthState findValueByNumber(int number) {
              return ResiprationHealthState.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return is.hellos.demos.models.protos.RespirationHealth.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResiprationHealthState[] VALUES = values();

    public static ResiprationHealthState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ResiprationHealthState(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:hello.ResiprationHealthState)
  }

  public interface RespirationStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hello.RespirationStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string device_id = 1;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>optional string device_id = 1;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>optional string device_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>optional .hello.ResiprationHealthState health_state = 2;</code>
     */
    boolean hasHealthState();
    /**
     * <code>optional .hello.ResiprationHealthState health_state = 2;</code>
     */
    is.hellos.demos.models.protos.RespirationHealth.ResiprationHealthState getHealthState();

    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code hello.RespirationStatus}
   */
  public static final class RespirationStatus extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hello.RespirationStatus)
      RespirationStatusOrBuilder {
    // Use RespirationStatus.newBuilder() to construct.
    private RespirationStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RespirationStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RespirationStatus defaultInstance;
    public static RespirationStatus getDefaultInstance() {
      return defaultInstance;
    }

    public RespirationStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RespirationStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              deviceId_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              is.hellos.demos.models.protos.RespirationHealth.ResiprationHealthState value = is.hellos.demos.models.protos.RespirationHealth.ResiprationHealthState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                healthState_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return is.hellos.demos.models.protos.RespirationHealth.internal_static_hello_RespirationStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return is.hellos.demos.models.protos.RespirationHealth.internal_static_hello_RespirationStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              is.hellos.demos.models.protos.RespirationHealth.RespirationStatus.class, is.hellos.demos.models.protos.RespirationHealth.RespirationStatus.Builder.class);
    }

    public static com.google.protobuf.Parser<RespirationStatus> PARSER =
        new com.google.protobuf.AbstractParser<RespirationStatus>() {
      public RespirationStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RespirationStatus(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RespirationStatus> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DEVICE_ID_FIELD_NUMBER = 1;
    private java.lang.Object deviceId_;
    /**
     * <code>optional string device_id = 1;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string device_id = 1;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEALTH_STATE_FIELD_NUMBER = 2;
    private is.hellos.demos.models.protos.RespirationHealth.ResiprationHealthState healthState_;
    /**
     * <code>optional .hello.ResiprationHealthState health_state = 2;</code>
     */
    public boolean hasHealthState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .hello.ResiprationHealthState health_state = 2;</code>
     */
    public is.hellos.demos.models.protos.RespirationHealth.ResiprationHealthState getHealthState() {
      return healthState_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      deviceId_ = "";
      healthState_ = is.hellos.demos.models.protos.RespirationHealth.ResiprationHealthState.NOBODY_PRESENT;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, healthState_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, healthState_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static is.hellos.demos.models.protos.RespirationHealth.RespirationStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static is.hellos.demos.models.protos.RespirationHealth.RespirationStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static is.hellos.demos.models.protos.RespirationHealth.RespirationStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static is.hellos.demos.models.protos.RespirationHealth.RespirationStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static is.hellos.demos.models.protos.RespirationHealth.RespirationStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static is.hellos.demos.models.protos.RespirationHealth.RespirationStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static is.hellos.demos.models.protos.RespirationHealth.RespirationStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static is.hellos.demos.models.protos.RespirationHealth.RespirationStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static is.hellos.demos.models.protos.RespirationHealth.RespirationStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static is.hellos.demos.models.protos.RespirationHealth.RespirationStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(is.hellos.demos.models.protos.RespirationHealth.RespirationStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hello.RespirationStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hello.RespirationStatus)
        is.hellos.demos.models.protos.RespirationHealth.RespirationStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return is.hellos.demos.models.protos.RespirationHealth.internal_static_hello_RespirationStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return is.hellos.demos.models.protos.RespirationHealth.internal_static_hello_RespirationStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                is.hellos.demos.models.protos.RespirationHealth.RespirationStatus.class, is.hellos.demos.models.protos.RespirationHealth.RespirationStatus.Builder.class);
      }

      // Construct using is.hellos.demos.models.protos.RespirationHealth.RespirationStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        healthState_ = is.hellos.demos.models.protos.RespirationHealth.ResiprationHealthState.NOBODY_PRESENT;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return is.hellos.demos.models.protos.RespirationHealth.internal_static_hello_RespirationStatus_descriptor;
      }

      public is.hellos.demos.models.protos.RespirationHealth.RespirationStatus getDefaultInstanceForType() {
        return is.hellos.demos.models.protos.RespirationHealth.RespirationStatus.getDefaultInstance();
      }

      public is.hellos.demos.models.protos.RespirationHealth.RespirationStatus build() {
        is.hellos.demos.models.protos.RespirationHealth.RespirationStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public is.hellos.demos.models.protos.RespirationHealth.RespirationStatus buildPartial() {
        is.hellos.demos.models.protos.RespirationHealth.RespirationStatus result = new is.hellos.demos.models.protos.RespirationHealth.RespirationStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.healthState_ = healthState_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof is.hellos.demos.models.protos.RespirationHealth.RespirationStatus) {
          return mergeFrom((is.hellos.demos.models.protos.RespirationHealth.RespirationStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(is.hellos.demos.models.protos.RespirationHealth.RespirationStatus other) {
        if (other == is.hellos.demos.models.protos.RespirationHealth.RespirationStatus.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000001;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (other.hasHealthState()) {
          setHealthState(other.getHealthState());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        is.hellos.demos.models.protos.RespirationHealth.RespirationStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (is.hellos.demos.models.protos.RespirationHealth.RespirationStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object deviceId_ = "";
      /**
       * <code>optional string device_id = 1;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string device_id = 1;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_id = 1;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_id = 1;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_id = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }

      private is.hellos.demos.models.protos.RespirationHealth.ResiprationHealthState healthState_ = is.hellos.demos.models.protos.RespirationHealth.ResiprationHealthState.NOBODY_PRESENT;
      /**
       * <code>optional .hello.ResiprationHealthState health_state = 2;</code>
       */
      public boolean hasHealthState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .hello.ResiprationHealthState health_state = 2;</code>
       */
      public is.hellos.demos.models.protos.RespirationHealth.ResiprationHealthState getHealthState() {
        return healthState_;
      }
      /**
       * <code>optional .hello.ResiprationHealthState health_state = 2;</code>
       */
      public Builder setHealthState(is.hellos.demos.models.protos.RespirationHealth.ResiprationHealthState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        healthState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .hello.ResiprationHealthState health_state = 2;</code>
       */
      public Builder clearHealthState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        healthState_ = is.hellos.demos.models.protos.RespirationHealth.ResiprationHealthState.NOBODY_PRESENT;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hello.RespirationStatus)
    }

    static {
      defaultInstance = new RespirationStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hello.RespirationStatus)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hello_RespirationStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hello_RespirationStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030respiration_health.proto\022\005hello\"n\n\021Res" +
      "pirationStatus\022\021\n\tdevice_id\030\001 \001(\t\0223\n\014hea" +
      "lth_state\030\002 \001(\0162\035.hello.ResiprationHealt" +
      "hState\022\021\n\ttimestamp\030\003 \001(\003*h\n\026Resipration" +
      "HealthState\022\022\n\016NOBODY_PRESENT\020\000\022\025\n\021PERSO" +
      "N_IS_PRESENT\020\001\022#\n\037PERSON_IS_PRESENT_NOT_" +
      "BREATHING\020\002B2\n\035is.hellos.demos.models.pr" +
      "otosB\021RespirationHealth"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hello_RespirationStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hello_RespirationStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hello_RespirationStatus_descriptor,
        new java.lang.String[] { "DeviceId", "HealthState", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
